### PR TITLE
fix weird focus outline on chef modals

### LINKED ISSUE #2371: chrome weird focus outline.
## Overview
When using Chrome, our delete modals and update project modals have weird focus outlines. This did not seem to be an issue in older versions of Chrome.

### Delete User
delete-user

### Delete Team
delete-team

### Delete Token
delete-token

### Update Projects
update-projects

### PR DESCRIPTION
**Pull request by susanev**
### :nut_and_bolt: Description: What code changed, and why?
in chrome the focus of our chef modals was displaying super weird
i also noticed that we were putting focus on a non-interactive element (div)
this changes the focus to be on the first interactive element (close button)
which also resolves the weird focus outline issue

... and i forgot about the locked modals
so added a case for that, if anyone has a better way to do that please let me know

### :chains: Related Resources
fixes #2371

### :+1: Definition of Done
no more weird focus outline
everything still works

### :athletic_shoe: How to Build and Test the Change
`make update-ui-lib` from `components/automate-ui`
`rebuild components/automate-ui-devproxy`

### :white_check_mark: Checklist

- [x] I have read the [CONTRIBUTING document](https://github.com/chef/automate/blob/master/CONTRIBUTING.md).
- [ ] Tests added/updated?
- [ ] Docs added/updated?
- [x] All commits have been signed-off for the [Developer Certification of Origin](https://github.com/chef/chef/blob/master/CONTRIBUTING.md#developer-certification-of-origin-dco).

### :camera: Screenshots, if applicable
this is just one example, it was happening on all the chef modals

#### before
before

#### after
after

### CODE REVIEW

**Comment by msorens** [comment]
FYI: You can just use `make update-ui-lib` instead of `scripts/build_chef_ui_lib && npm run copy-ui-lib`.

File: components/chef-ui-library/src/molecules/chef-modal/chef-modal.tsx [hunk 1]
```diff
@@ -115,13 +115,17 @@ export class ChefModal {
...
+      const focusElement =
+        (this.locked ? this.el.getElementsByClassName('modal').item(0) :
+        this.el.getElementsByClassName('close').item(0).firstElementChild) as HTMLElement;
+
+      const focusElementInterval = setInterval(() => {
+        focusElement.focus();
+        if (focusElement === document.activeElement) {
+          clearInterval(focusElementInterval);
         }
       }, 1);
```
Comment (msorens) [inline components/chef-ui-library/src/molecules/chef-modal/chef-modal.tsx]: We could do this more concisely unless there is a reason to be waiting until the element gets focus (which is what the conditional checks for) ...? So with this change sometimes the close button would get outlined and sometimes not, but the initial problem is still corrected.
```suggestion
      setTimeout(() => focusElement.focus(), 1);
```

**Comment by msorens** [comment]
Don't quite see the rationale for your comment, @SEAjamieD . Using the ternary is more functional style coding which is usually preferred.

File: components/chef-ui-library/src/molecules/chef-modal/chef-modal.tsx (hunk 1 above)
Comment (susanev) [reply components/chef-ui-library/src/molecules/chef-modal/chef-modal.tsx]: yah idk that code was already there? i assumed it was needed...

**Comment by SEAjamieD** [comment]
> Don't quite see the rationale for your comment, @SEAjamieD . Using the ternary is more functional style coding which is usually preferred.

@msorens - I love ternary's.  I must have misunderstood some commentary on my code in the past that suggested not to use them.  Thanks for the note!
