### PR TITLE
Be explicit about dependencies on coreutils

### LINKED ISSUE #4105: Automate deploy fails when the linux hab user comes from external auth instead of local accounts
## Describe the bug

Automate is unable to complete the deployment step if `hab` the hab user is coming from an external auth like LDAP in Linux instead of as a local account in `/etc/passwd`.

Initially, we saw errors from `useradd` complaining that the user already completed and a workaround was added #4078 to get past this.  

After the workaround, we now see the following error when running `CHEF_AUTOMATE_SKIP_HAB_USER=true chef-automate deploy`

```
Jul 20 17:57:26 HOSTNAME.com hab[30310]: deployment-service.default(O): failed to start server: failed to initialize secret store: user lookup: user: unknown user hab
```

The underlying problem appears to be caused by GoLang not using libc to query for user and group UID/GIDs and instead only pulling them from `/etc/passwd` and `/etc/group`. This will cause the deploy to fail as it can't find the `hab` user and attempts to create it via `useradd`. Which will then fail as it already exists in LDAP, also any other code that attempts to fetch the `hab` UID/GID` will have problems as it won't get a valid ID.

## To Reproduce

1. configure Linux to use external LDAP user accounts (via /etc/nsswitch.conf)
2. create a `hab` user in LDAP
3. Attempt to install Automate `chef-automate deploy`, latest current version will throw an error 
    
    ```
    Creating Habitat user and group
    Error: setup failed: creating hab user failed: "useradd: user 'hab' already exists\n": exit status 9  
    DeployError: Unable to install, configure and start the
    ```

4. If using a version from the dev channel `CHEF_AUTOMATE_SKIP_HAB_USER=true chef-automate deploy` to skip the `useradd` error and get the error about the `secret store` and `hab`.

    ```
    Jul 20 17:57:26 HOSTNAME.com hab[30310]: deployment-service.default(O): failed to start server: failed to initialize secret store: user lookup: user: unknown user hab
    ```

## Expected behavior
Automate will complete the deployment successfully.

## Versions (please complete the following information):
- OS: RHEL 7
- Browser: N/A
- Automate Build Number: latest current and dev builds

### PR DESCRIPTION
**Pull request by jaym**
Be explicit about dependencies on coreutils

We want to depend on coreutils as it will be able correctly look up UIDs
and GIDs when it comes to LDAP.

Don't use busybox

Follow up to #4110
Fixes #4105

### CODE REVIEW

File: components/automate-elasticsearch/habitat/plan.sh [hunk 1]
```diff
@@ -15,8 +15,7 @@ pkg_build_deps=(
   core/patchelf
 )
 pkg_deps=(
-  core/coreutils-static
-  core/busybox-static
```
Comment (stevendanna) [inline components/automate-elasticsearch/habitat/plan.sh:19]: Do we know why busybox was here at all? Just copy/pasta?

Comment (jaym) [reply components/automate-elasticsearch/habitat/plan.sh:19]: i think i copy-pasta'd it last week

File: lib/user/lookup.go [hunk 2]
```diff
@@ -0,0 +1,237 @@
...
+			}
+		}
+	}
+
+	return getentLookupProvider{
+		getentPath: getentPath,
+	}
+}
+
+func (g getentLookupProvider) Lookup(username string) (*User, error) {
```
Comment (stevendanna) [inline lib/user/lookup.go:151]: not required at all for this PR, but from here down in this file there are a number of opportunities to pull out some well named constants and potentially extract some common code.  But I think it is fine as-is as well.

Comment (jaym) [reply lib/user/lookup.go:151]: that was the hope, but the error type got in the way
