### PR TITLE
Part of #3332: fix diagnostics left overs -- projects and rules

### LINKED ISSUE #3445: clean up left over projects and project rules from diagnostics
see #3332

### PR DESCRIPTION
**Pull request by srenatus**
### :nut_and_bolt: Description: What code changed, and why?

We had a bug or two in our diagnostics code that caused projects and rules to stick around after a successful run. Please see the first commit for the fix. The rest of the PR is fixing other occurrences, and minor issues.

⚠️ This doesn't fix these left-overs:
- Token `This token was generated by the chef-automate diagnostic tool. It has admin level access on the entire Automate API.`
- Policy `admin policy for token 1735392e-b4cf-42eb-bf58-611b17e28241`

They are created using a different code-flow and hence their removal can be tackled separately.

### :chains: Related Resources

- #3332 
- Fixes #3445 

### :+1: Definition of Done

Run diagnostics, see the project **not** left over.

### :athletic_shoe: How to Build and Test the Change

- `rebuild components/automate-cli`
- `chef-automate diagnostics run iam`
- observe existing projects

### :white_check_mark: Checklist

- [ ] I have read the [CONTRIBUTING document](https://github.com/chef/automate/blob/master/CONTRIBUTING.md).
- [ ] Tests added/updated?
- [ ] Docs added/updated?
- [ ] All commits have been signed-off for the [Developer Certification of Origin](https://github.com/chef/chef/blob/master/CONTRIBUTING.md#developer-certification-of-origin-dco).

### CODE REVIEW

File: components/automate-cli/pkg/diagnostics/integration/iam_projects.go [hunk 1]
```diff
@@ -130,16 +130,19 @@ func GetProject(tstCtx diagnostics.TestContext, id string) (*ProjectInfo, error)
...
-		tstCtx.DoLBRequest(
-			fmt.Sprintf("/apis/iam/v2/projects/%s", id),
-			lbrequest.WithMethod("DELETE"),
-		)).Error()
+// DeleteProjectWithRule deletes the project with the given id and its associated rule
+func DeleteProjectWithRule(tstCtx diagnostics.TestContext, projectID, ruleID string) error {
+	if err := MustJSONDecodeSuccess(tstCtx.DoLBRequest(
+		fmt.Sprintf("/apis/iam/v2/projects/%s/rules/%s", projectID, ruleID),
+		lbrequest.WithMethod("DELETE"),
+	)).WithValue(&struct{}{}); err != nil {
```
Comment (srenatus) [inline components/automate-cli/pkg/diagnostics/integration/iam_projects.go:138]: `.Error()` was only checking the err of `resp, err := ...`. Using `WithValue(&struct{}{})`, we ignore whatever's returned (the struct we marshal into has no fields), but we leverage that the `WithValue` method does check the HTTP status return for code 200.

File: components/automate-cli/pkg/diagnostics/integration/iam_projects.go [hunk 2]
```diff
@@ -130,16 +130,19 @@ func GetProject(tstCtx diagnostics.TestContext, id string) (*ProjectInfo, error)
 	return &projectInfo, nil
 }
 
-// DeleteProject deletes the project with the given id
-func DeleteProject(tstCtx diagnostics.TestContext, id string) error {
-	// any associated rules are cascade-deleted with the project
```
Comment (srenatus) [inline components/automate-cli/pkg/diagnostics/integration/iam_projects.go:135]: Turns out this wasn't the case. It return `err == nil`, but `resp.StatusCode == 400` because the project had a rule.

File: components/automate-cli/pkg/diagnostics/integration/iam_projects.go (hunk 1 above)
Comment (bcmdarroch) [reply components/automate-cli/pkg/diagnostics/integration/iam_projects.go:138]: good catch 👍

File: components/automate-cli/pkg/diagnostics/integration/helpers.go [hunk 3]
```diff
@@ -6,7 +6,7 @@ import (
 	"net/http"
 	"time"
 
-	uuid "github.com/gofrs/uuid"
+	uuid "github.com/chef/automate/lib/uuid4"
```
Comment (bcmdarroch) [inline components/automate-cli/pkg/diagnostics/integration/helpers.go:9]: what's this needed for?

Comment (tylercloke) [reply components/automate-cli/pkg/diagnostics/integration/helpers.go:9]: He's just updating to use our wrapper of the UUID library (which I didn't know we had until now, nice!). We should probably be using that everywhere.
