### PR TITLE
automate-3081 ui flicker on applications tab

### LINKED ISSUE #3081: UI flicker on Applications tab
## Describe the bug

When moving between "OK" and "Disconnected" nodes, the UI moves from the loading spinner, to the _old_ data, to the _new_ data, with a visible redraw when the new data is finally shown.  Please see the following video:
 
output

## To Reproduce
- Go to Application Tab
- Select "OK" filter
- Select "Disconnected" filter.

Note I am very far from this A2 server, so high-network latency may help reproduce it.

## Expected behavior

- Smooth as butter, no flicker.

### PR DESCRIPTION
**Pull request by tarablack01**
### :nut_and_bolt: Description: What code changed, and why?
When moving between "OK" and "Disconnected" nodes, the UI moves from the loading spinner, to the old data, to the new data, with a visible redraw when the new data is finally shown.

### :chains: Related Resources
fixes #3081

### :+1: Definition of Done
Smooth as butter, no flicker.

### :athletic_shoe: How to Build and Test the Change
hab studio enter
export DEVPROXY_URL=localhost
build components/automate-ui-devproxy
start_automate_ui_background
start_all_services
applications_populate_database

Go to Application Tab
Select "OK" filter
Select "Disconnected" filter.
Note I am very far from this A2 server, so high-network latency may help reproduce it.

### :white_check_mark: Checklist

- [ ] I have read the [CONTRIBUTING document](https://github.com/chef/automate/blob/master/CONTRIBUTING.md).
- [ ] Tests added/updated?
- [ ] Docs added/updated?
- [x] All commits have been signed-off for the [Developer Certification of Origin](https://github.com/chef/chef/blob/master/CONTRIBUTING.md#developer-certification-of-origin-dco).

### :camera: Screenshots, if applicable
Screen Shot 2020-05-18 at 5 28 22 PM
Screen Shot 2020-05-18 at 5 28 45 PM
Screen Shot 2020-05-18 at 5 28 51 PM

### CODE REVIEW

**Comment by tarablack01** [comment]
@SEAjamieD thanks for catching that bug! I'll fix it 👍🏻

File: components/automate-ui/src/app/pages/service-groups/service-groups.component.ts [hunk 1]
```diff
@@ -246,22 +246,20 @@ export class ServiceGroupsComponent implements OnInit, OnDestroy {
...
-            });
-          }
-        });
-      }
+    this.store.select(selectedServiceGroupStatus).subscribe((sSgStatus) => {
+      this.store.select(serviceGroupsStatus).subscribe((sgStatus) => {
+        if (sgStatus === 'loadingSuccess' && sSgStatus === 'loadingSuccess') {
+          this.serviceGroupsList$.subscribe((serviceGroups) => {
+            if (serviceGroups.length > 0) {
+              this.store.select(selectedServiceGroupHealth).subscribe((sgHealth) => {
```
Comment (msorens) [inline components/automate-ui/src/app/pages/service-groups/service-groups.component.ts:254]: This is a big red flag that would eventually cause memory problems: you should almost never use nested subscriptions and this one is 4 levels deep! Use a `combineLatest` instead to make it a single subscription.

Not directly related: be sure to add a `takeUntil(this.isDestroyed)` before the `subscribe` as well. Please review the rest of the file as there are a couple others missing as well.

File: components/automate-ui/src/app/pages/service-groups/service-groups.component.ts [hunk 2]
```diff
@@ -246,21 +246,20 @@ export class ServiceGroupsComponent implements OnInit, OnDestroy {
...
+      if (sgStatus === 'loadingSuccess' && sSgStatus === 'loadingSuccess') {
+          if (serviceGroups.length > 0) {
+              if (sgHealth.total === 0) {
+                this.onServiceGroupSelect(null, serviceGroups[0].id);
               }
-            });
           }
-        });
       }
     });
```
Comment (msorens) [inline components/automate-ui/src/app/pages/service-groups/service-groups.component.ts:264]: With the `combineLatest` clearing up the nested subscription problem, the code is sufficient, but we can clean it up a bit further. Using the convention of applying filters instead of using conditionals, here we can substantially reduce the cyclomatic complexity by eliminating all the remaining nested conditionals.
```
      filter(([sSgStatus, sgStatus, serviceGroups, sgHealth]) =>
        sgStatus === EntityStatus.loadingSuccess
        && sSgStatus === EntityStatus.loadingSuccess
        && serviceGroups.length > 0
        && sgHealth.total === 0
      ),
      takeUntil(this.isDestroyed)
    ).subscribe(([_sSgStatus, _sgStatus, serviceGroups, _sgHealth]) =>
      this.onServiceGroupSelect(null, serviceGroups[0].id));
```

Comment (scottopherson) [reply components/automate-ui/src/app/pages/service-groups/service-groups.component.ts:264]: @msorens speaking of conventions, I've noticed a mixture of `this.isDestroyed$` and `this.isDestroyed`. I'm not sure what we'd want to prefer using (other than `isDestroyed$` seems more prevalent I think?)

Should `$` be appended to only `Observable` types, or appended to any type that can be subscribed to? (`Observable`, `Subject`, `ReplaySubject`, etc). I lean towards the latter at the moment

Comment (msorens) [reply components/automate-ui/src/app/pages/service-groups/service-groups.component.ts]: Great question, @scottopherson ! I have been kicking that can down the road because I thought it was just for Observables but was not really sure... A quick web search just now revealed people say Observable in one breath but then usually go on to add "... and streams". So I am happy to oblige and go with your suggestion of any type that can be subscribed to. 👍

Comment (scottopherson) [reply components/automate-ui/src/app/pages/service-groups/service-groups.component.ts]: @msorens ah yea, I'm seeing the "and streams" as well.
Yeah to me seems like `$` is useful for immediately identifying what can be done with a certain value (`subscribe`, `useWith$ | async`, use within `pipe` chain) and possible pitfalls that can occur with said value (memory leaks). Though seeing the types for these values in our IDEs helps with that as well 🤷
