### PR TITLE
Fixed for create user model username input is exposed but it should be hidden 

### LINKED ISSUE #1668: ID field exposed when it should be hidden
## Overview
On the auth related (team, token, project) create flows their is a hidden ID input. It is hidden until the user takes a discrete action to expose it. Currently, if you use the create form twice in a row the ID field is exposed when it should be hidden.

This is a problem for both the generic [Create Object Modal](https://github.com/chef/automate/blob/master/components/automate-ui/src/app/components/create-object-modal/create-object-modal.component.ts) and the [Create User Modal](https://github.com/chef/automate/blob/master/components/automate-ui/src/app/page-components/create-user-modal/create-user-modal.component.ts) 

## Repro steps
- create 1 thing (e.g., project)
- edit the id while creating
- then create another thing of the same type
- notice that the id field is exposed (but it should be hidden)

### PR DESCRIPTION
**Pull request by vinay033**
Signed-off-by: vinay033 <vsharma@chef.io>

### :nut_and_bolt: Description: What code changed, and why?
when creating a user, if you expose the username input then cancel or submit. then try and create another user the username input is exposed but it should be hidden until they take action on the edit username button.
I have added some minor changes to fix this.

### :chains: Related Resources
fixes #1668
### :+1: Definition of Done
I have added some changes to `create user model` to fix this issue.
### :athletic_shoe: How to Build and Test the Change
```
STEP 1
inside the hab studio

[default:/src:0]# build components/automate-ui-devproxy/
[default:/src:0]# start_automate_ui_background
[default:/src:0]# start_all_services

STEP 2
open new window
go to automate UI path

$ cd components/automate-ui
and run the command 

npm run serve:hab
```
### :white_check_mark: Checklist

- [ ] I have read the [CONTRIBUTING document](https://github.com/chef/automate/blob/master/CONTRIBUTING.md).
- [ ] Tests added/updated?
- [ ] Docs added/updated?
- [ ] All commits have been signed-off for the [Developer Certification of Origin](https://github.com/chef/chef/blob/master/CONTRIBUTING.md#developer-certification-of-origin-dco).

### :camera: Screenshots
Create-user-model

### CODE REVIEW

File: components/automate-ui/src/app/page-components/create-user-modal/create-user-modal.component.ts [hunk 1]
```diff
@@ -94,6 +94,7 @@ export class CreateUserModalComponent implements OnInit, OnDestroy {
   }
 
   closeCreateModal(): void {
+    this.modifyUsername = false;
```
Comment (msorens) [inline components/automate-ui/src/app/page-components/create-user-modal/create-user-modal.component.ts:97]: Hi, @vinay033! This is certainly the correct line to add, but all the similar resetting is done in this block:
https://github.com/chef/automate/blob/19339b281fc4400eafb3124c11099b5475606a2e/components/automate-ui/src/app/page-components/create-user-modal/create-user-modal.component.ts#L57-L63

I was wondering if there was a reason why you added it in `closeCreateModal` instead? If not, would you mind moving it when you have a chance?

Comment (vinay033) [reply components/automate-ui/src/app/page-components/create-user-modal/create-user-modal.component.ts:97]: I focused on close the modal and then I have added these changes.
but I will create a new one PR to incorporate this.

Comment (vinay033) [reply components/automate-ui/src/app/page-components/create-user-modal/create-user-modal.component.ts:97]: review comment incorporated 
PR: https://github.com/chef/automate/pull/3678
